# list1 = ['you are python','good']
# print ( len(list1))
# print( list1[0] )
# list2 = ('you are python')
# print(len(list2))
# print(list2[0])
# list3 = 'you are python'
# print (len(list3))
# print (list3[0])
a = open(r'C:\Users\Administrator\Desktop\test\110.txt')
data = a.read()
print(data)
b = open(r'C:\Users\Administrator\Desktop\test\120.txt','w')
b.write(data)
a.close()
b.close()
c=open(r'C:\Users\Administrator\Desktop\test\120.txt')
data2 = c.read()
print(data2)